#!/bin/bash
set -euo pipefail

# This script takes no PCAP argument: it is a detection-engineering design
# document, not a live analysis. Every "test scenario" and "would detect"
# line below reuses the real, already-verified figures from 6-kill_chain.sh
# and its underlying scripts (1-phishing_click.sh, 3-dns_tunnel.sh,
# 4-lateral_movement.sh, 5-vpn_pivot.sh) rather than the illustrative numbers
# from the task's own example output.

echo "================================================================"
echo "   DETECTION ENGINEERING PLAN"
echo "================================================================"
echo ""

#============= DETECTION 1: C2 BEACONING ================
echo "[*] Detection 1: C2 Beaconing"
echo "    Type: Frequency-based behavioral detection"
echo "    Logic:"
echo "      If same src_ip -> same dst_ip > 10 times in 3600 seconds"
echo "      AND interval_stddev < interval_mean * 0.15"
echo "      THEN alert: Possible C2 beaconing"
echo ""
echo "    Implementation options:"
echo "      SIEM rule:        aggregate connection events by (src_ip, dst_ip) over a"
echo "                        60-minute sliding window; compute count, mean interval"
echo "                        and stddev in the query itself (e.g. Splunk 'stats' /"
echo "                        Sigma 'timeframe' + 'count()' correlation rule)."
echo "      Zeek script:      hook conn.log, keep a per-(orig_h,resp_h) table of"
echo "                        connection start times, evaluate on each new entry."
echo "      Python scheduled: cron job queries flow/proxy logs every N minutes,"
echo "                        groups by source-destination pair, flags on threshold."
echo "      NetFlow analytics: equivalent grouping on flow records where full packet"
echo "                        capture isn't retained long-term."
echo ""
echo "    Data source: PCAP-derived session logs, Zeek conn.log, NetFlow or proxy logs"
echo ""
echo "    Test scenario (real, from c2_beaconing.pcap):"
echo "      10.10.2.15 connects to 91.234.99.107 24 times, mean interval 299.8s,"
echo "      stddev 5.3s (1.8% of mean) — well under the 15% threshold, so this"
echo "      rule would have fired on this exact evidence."
echo ""
echo "    Attack phase detected: Phase 3 (C2 Beaconing)"
echo "    Expected false positives: software update clients, monitoring agents and"
echo "      backup tools that poll on a fixed schedule can be just as regular;"
echo "      requires allow-listing against a known-good baseline (Task 0)."
echo ""
#============= END DETECTION 1 ================

#============= DETECTION 2: DNS QUERY LENGTH ANOMALY ================
echo "[*] Detection 2: DNS Query Length Anomaly"
echo "    Type: Structural/length-based detection"
echo "    Logic:"
echo "      If left-most DNS label length > 40"
echo "      AND query type is TXT"
echo "      AND repeated queries target the same base domain"
echo "      THEN alert: Possible DNS tunneling"
echo ""
echo "    Why length matters: a legitimate hostname label is short and human-chosen"
echo "      (e.g. 'www', 'mail01'); DNS tunneling tools encode arbitrary binary data"
echo "      into the label using base32/base64-style alphabets, which pushes label"
echo "      length toward the DNS protocol's own 63-character-per-label ceiling and"
echo "      produces no readable word — length plus encoded-looking content together"
echo "      are the signal, not length alone."
echo ""
echo "    Data source: DNS resolver query logs or passive DNS capture"
echo ""
echo "    Test scenario (real, from dns_exfil.pcap):"
echo "      billing-srv-01 sends TXT queries to data-sync.meddefense-portal[.]com"
echo "      with subdomain labels observed up to the encoded-payload length range"
echo "      documented in 3-dns_tunnel.sh's Anomalous Query Analysis section."
echo ""
echo "    Attack phase detected: Phase 7 (DNS Exfiltration)"
echo "    Expected false positives: some CDN and email-authentication (DKIM) TXT"
echo "      records use long, encoded-looking labels legitimately; requires an"
echo "      allow-list of known infrastructure domains."
echo ""
#============= END DETECTION 2 ================

#============= DETECTION 3: VPN GEO-ANOMALY ================
echo "[*] Detection 3: VPN Geo-Anomaly"
echo "    Type: Contextual/geolocation-based detection"
echo "    Logic:"
echo "      If VPN source country or ASN is not in the organization's expected list"
echo "      AND the account has no prior successful login history from that geography"
echo "      THEN alert: Suspicious VPN login"
echo ""
echo "    Required data source: a maintained expected-geography/ASN list for the"
echo "      organization, a per-account login-history table (country/ASN seen at"
echo "      each prior successful auth), and either a commercial IP-geolocation"
echo "      feed or WHOIS/RDAP lookups at login time — none of which a PCAP alone"
echo "      provides; this detection must live at the VPN gateway or IdP, not in"
echo "      network capture."
echo ""
echo "    Test scenario (real, from full_timeline.pcap / 5-vpn_pivot.sh):"
echo "      dmarsh authenticates to the VPN from 154.118.42.89, live WHOIS-resolved"
echo "      to NG / AS37340 (Spectranet) — geographically distant from MedDefense's"
echo "      expected Midwest US operating region and with 2fa=none recorded in the"
echo "      session's own payload marker."
echo ""
echo "    Attack phase detected: Phase 4 (External VPN Pivot)"
echo "    Expected false positives: legitimate travel, remote contractors, or"
echo "      mobile-carrier IP reassignment routing through an unexpected ASN."
echo ""
#============= END DETECTION 3 ================

#============= DETECTION 4: CROSS-ROLE RDP ================
echo "[*] Detection 4: Cross-Role RDP"
echo "    Type: Role/context-based detection"
echo "    Logic:"
echo "      If source account role is clinical/end-user"
echo "      AND destination subnet is server-tier"
echo "      AND protocol is RDP"
echo "      THEN alert: Possible lateral movement"
echo ""
echo "    How to detect it:"
echo "      From packet metadata alone: source/destination IP subnet membership"
echo "      (e.g. 10.10.2.0/24 clinical vs 10.10.1.0/24 server) plus destination"
echo "      port 3389 is directly observable, as in 4-lateral_movement.sh — but the"
echo "      account's ROLE is not in the packet; it must be joined against an"
echo "      authentication log or directory-service record (e.g. Windows Event ID"
echo "      4624 plus an AD group lookup) to know that dmarsh is a clinical account."
echo ""
echo "    Data source: network flow/PCAP for the connection, directory service"
echo "      (AD/LDAP) for account role, Windows Security Event Log for logon type"
echo ""
echo "    Test scenario (real, from lateral_movement.pcap):"
echo "      WS-NURSE-04 (10.10.2.15, clinical subnet) opens an RDP/NLA session to"
echo "      billing-srv-01 (10.10.1.10, server subnet) as account dmarsh — a"
echo "      pattern the Task 0 baseline never shows occurring normally."
echo ""
echo "    Attack phase detected: Phase 5 (Lateral Movement)"
echo "    Expected false positives: legitimate IT/helpdesk staff using a clinical"
echo "      workstation for remote administration; requires the role table to be"
echo "      accurate and kept current."
echo ""
#============= END DETECTION 4 ================

#============= DETECTION 5: DNS TUNNELING TXT QUERY PATTERN ================
echo "[*] Detection 5: DNS Tunneling TXT Query Pattern"
echo "    Type: Rate-based behavioral detection"
echo "    Logic:"
echo "      Count TXT queries per source per base domain in a sliding window."
echo "      If count > 10 in 120 seconds AND encoded-looking labels are present,"
echo "      THEN alert: Possible DNS tunneling"
echo ""
echo "    Data source: DNS resolver query logs or passive DNS capture"
echo ""
echo "    Test scenario (real, from dns_exfil.pcap):"
echo "      billing-srv-01 sends 120 anomalous TXT queries to"
echo "      data-sync.meddefense-portal[.]com over roughly a 30-minute window,"
echo "      well above 10 queries per 120 seconds sustained (see 3-dns_tunnel.sh"
echo "      Exfiltration Rate section for the exact figures)."
echo ""
echo "    Attack phase detected: Phase 7 (DNS Exfiltration)"
echo "    Expected false positives: legitimate high-frequency TXT use (e.g. SPF/"
echo "      DKIM verification bursts during mail server startup) targeting a"
echo "      single domain."
echo ""
#============= END DETECTION 5 ================

#============= DETECTION 6: TLS TO CAMPAIGN LOOKALIKE DOMAIN ================
echo "[*] Detection 6: TLS to Recently Observed Lookalike Domain"
echo "    Type: IOC/reputation-based detection"
echo "    Logic (no live domain-age feed required):"
echo "      Maintain a first-seen table: {domain, first_seen_timestamp, source}"
echo "      populated from prior phishing-campaign IOCs (4x00) and any TLS SNI or"
echo "      DNS query newly observed on the network."
echo "      If TLS SNI matches an entry in the known-IOC list (meddefense-portal.com,"
echo "      data-sync.meddefense-portal.com),"
echo "      OR the SNI's registrable domain closely resembles ('meddefense.com')"
echo "      an organization-owned domain but is not itself on the owned-domains list,"
echo "      THEN alert: Possible phishing/lookalike TLS session, enrich with"
echo "      campaign context from the first-seen table."
echo ""
echo "    Data source: TLS SNI from network capture/proxy logs, the organization's"
echo "      own domain inventory, and the IOC list carried over from 4x00"
echo ""
echo "    Test scenario (real, from phishing_click.pcap):"
echo "      WS-NURSE-04 establishes a TLS ClientHello with SNI"
echo "      meddefense-portal.com — an exact match against the IOC list from the"
echo "      4x00 email investigation, and a lookalike of the organization's real"
echo "      domain."
echo ""
echo "    Attack phase detected: Phase 2 (Credential Harvesting)"
echo "    Expected false positives: legitimately registered partner or vendor"
echo "      domains that happen to share a naming pattern; requires the"
echo "      owned-domains list to be complete and current."
echo ""
#============= END DETECTION 6 ================

#============= DETECTION COVERAGE UPDATE ================
echo "=== DETECTION COVERAGE UPDATE ==="
echo "Before packet analysis:"
echo "  campaign visible only as email IOCs (4x00): meddefense-portal.com,"
echo "  91.234.99.107 — no visibility into anything past the initial click."
echo ""
echo "After packet analysis:"
echo "  detections above cover phishing click (6), C2 beaconing (1), VPN geo-"
echo "  anomaly (3), cross-role RDP (4) and DNS exfiltration (2, 5) — 6 phases"
echo "  out of 7 in the kill chain now have a corresponding, evidence-grounded"
echo "  detection rule."
echo ""
echo "Remaining gaps:"
echo "  Phase 1 (initial access) still requires mail-gateway/endpoint telemetry —"
echo "    no network-layer detection can observe the click decision itself."
echo "  exact credential content cannot be recovered from encrypted TLS sessions;"
echo "    Detection 3 relies on VPN gateway/IdP-side auth outcome, not packet"
echo "    payload, for the real world (this evidence set's plaintext marker is"
echo "    specific to this dataset, not something a production TLS session exposes)."
echo "================================================================"
#============= END DETECTION COVERAGE UPDATE ================
