/*
 * Detection basis: 4x00 found the Email 5 lure PDF was generated by
 * wkhtmltopdf 0.12.6 and contained embedded credential-harvesting URLs.
 * Direct inspection of this project's own sample corpus (samples/*.pdf)
 * confirms both malicious samples share the wkhtmltopdf 0.12.6 producer
 * string plus a "/portal/login" URI path, while both benign samples use a
 * different PDF producer (Adobe PDF Library / Microsoft Print To PDF) and
 * contain no credential-harvesting path or parameter patterns at all.
 *
 * Design choice: the condition intentionally does NOT hardcode specific
 * campaign domains (meddefense-portal.com, medequip-supplies.net, etc.).
 * The researcher blog (researcher_blog_analysis.txt, Section 7) explicitly
 * warns that "indicator-based blocking will work for about one week;
 * operational-pattern detections will survive rotation" -- this rule
 * targets the structural pattern (PDF tooling fingerprint + credential-path
 * URL shape) so it keeps matching future HEALTHBANE lures even after the
 * domains in this specific sample set are burned and rotated.
 */

rule HEALTHBANE_Phishing_PDF
{
    meta:
        author         = "MedDefense SOC (4x02 intelligence-driven defense)"
        description    = "Detects PDF lures matching the HEALTHBANE phishing-kit pattern: wkhtmltopdf-generated PDFs embedding credential-harvesting URL paths"
        date           = "2026-04-27"
        reference       = "HEALTHBANE campaign, HC3-2026-HEALTHBANE-001; corroborated by MedDefense 4x00 findings and researcher_blog_analysis.txt Section 2-4"
        threat_level   = "high"
        confidence     = "high"

    strings:
        // PDF magic bytes -- required to even consider the file a PDF.
        $pdf_magic = "%PDF" ascii

        // wkhtmltopdf 0.12.6 is the kit's PDF-generation tool fingerprint,
        // confirmed identical across both malicious samples in this corpus
        // and in the Email 5 lure documented in 4x00. Both benign samples
        // use unrelated producers (Adobe PDF Library, Microsoft Print to
        // PDF), so this string alone already strongly separates the sets.
        $tool_fingerprint = "wkhtmltopdf" ascii

        // Credential-harvesting URL path fragments. Observed directly in
        // this corpus: both malicious PDFs embed a "/portal/login" link
        // annotation; the task's own instructions additionally call for
        // /verify and /enroll, which appear in other HEALTHBANE lures
        // documented in the intelligence sources (e.g. meddefense-benefits
        // .org/enroll, meddefense-portal.com/verify/staff) even though
        // this specific 2-file PDF sample only exercises /portal + /login.
        $path_verify = "/verify" ascii
        $path_login  = "/login" ascii
        $path_portal = "/portal" ascii
        $path_enroll = "/enroll" ascii

        // URL parameters used for per-victim tracking/capture, per HC3
        // and the researcher's kit analysis (id=<user>, token=<hex>).
        $param_token = "token=" ascii
        $param_id    = "id=" ascii

    condition:
        // Must actually be a PDF, must carry the kit's tooling fingerprint,
        // and must contain at least two of the credential-harvesting URL
        // signals above (path fragments and/or parameters, in any
        // combination) -- a single generic path or parameter alone is not
        // enough to avoid false positives on ordinary PDFs that happen to
        // link to an unrelated "/login" page.
        $pdf_magic at 0 and
        $tool_fingerprint and
        2 of ($path_verify, $path_login, $path_portal, $path_enroll, $param_token, $param_id)
}

/*
 * Test results (yara 9-yara_phishing_pdf.yar samples/), verified 2026-04-27:
 *
 *   HEALTHBANE_Phishing_PDF samples/healthbane_lure_02.pdf   -- MATCH (expected: true positive)
 *   HEALTHBANE_Phishing_PDF samples/phishing_sample.pdf      -- MATCH (expected: true positive)
 *   samples/clean_invoice.pdf                                -- no match (expected: true negative)
 *   samples/benign_invoice.pdf                                -- no match (expected: true negative)
 *
 * True positives: both phishing PDF samples detected via wkhtmltopdf
 * fingerprint + 2+ credential-harvesting URL signals (both hit /portal
 * and /login from the shared "/portal/login" link; phishing_sample.pdf
 * additionally hits id= and token=; healthbane_lure_02.pdf additionally
 * hits id=).
 * True negatives: both clean/benign invoice samples use unrelated PDF
 * producers (Adobe PDF Library 23.0, Microsoft: Print To PDF) and link
 * only to /vendor/statements and /billing/statements -- no tooling
 * fingerprint and zero credential-harvesting path/parameter hits.
 */
