#!/bin/bash
set -euo pipefail

echo "================================================================"
echo "   DETECTION GAP ANALYSIS - Stage 4 Techniques"
echo "================================================================"
echo ""

#============= GAP 1: PsExec ================
echo "GAP 1: T1021.002 PsExec Lateral Movement"
echo "  Hunt Finding: PsExec from WS-RECV-03 (non-admin workstation) using"
echo "    svc_healthsync, off-hours, against 3 production servers (4-hunt_psexec.sh)"
echo "  Why Missed: Missing rule -- Sysmon Event 1 (process creation) for this"
echo "    exact process was being collected the whole time; no Wazuh rule"
echo "    existed to evaluate source host against the admin baseline"
echo "  Data Source: Sysmon Event 1 (Process Create)"
echo "  Required Rule: alert when image/commandLine contains PsExec AND"
echo "    source host != WS-ADMIN-01 OR event time is outside 08:00-18:00 CDT"
echo "  Priority: P1"
echo ""

#============= GAP 2: LSASS ================
echo "GAP 2: T1003.001 LSASS Credential Access"
echo "  Hunt Finding: debug_tool.exe (path matches HC3 IOC) accessed lsass.exe"
echo "    twice, ~1 week apart, from WS-RECV-03 (6-hunt_credentials.sh)"
echo "  Why Missed: Missing rule -- Sysmon Event 10 was being collected, but"
echo "    no rule evaluated sourceImage against the standard process allowlist"
echo "  Data Source: Sysmon Event 10 (ProcessAccess)"
echo "  Required Rule: alert when TargetImage=lsass.exe AND sourceImage is NOT"
echo "    IN (csrss.exe, services.exe, svchost.exe, MsMpEng.exe, WmiPrvSE.exe,"
echo "    wininit.exe) -- NOT a raw GrantedAccess bitmask check: this dataset"
echo "    shows a legitimate services.exe access (0x101010) whose bitmask"
echo "    overlaps the advisory's own stated 0x0010 indicator, so bitmask"
echo "    matching alone would false-positive on known-good activity"
echo "  Priority: P1"
echo ""

#============= GAP 3: WMI ================
echo "GAP 3: T1047 WMI Remote Execution"
echo "  Hunt Finding: WmiPrvSE.exe spawned cmd.exe/powershell.exe on all 3"
echo "    target servers within ~30 min of each PsExec session (5-hunt_wmi.sh)"
echo "  Why Missed: Missing rule -- Sysmon Event 1 captured the parent-child"
echo "    relationship, but no rule flagged WmiPrvSE.exe spawning a shell"
echo "  Data Source: Sysmon Event 1 (Process Create), ParentImage field"
echo "  Required Rule: alert when ParentImage=WmiPrvSE.exe AND Image IN"
echo "    (cmd.exe, powershell.exe) -- per HC3's advisory this pattern \"has"
echo "    no legitimate baseline in the observed victim environments,\" so"
echo "    unlike the PsExec/PSRemoting rules this one needs no baseline"
echo "    comparison at all -- the occurrence itself is the indicator"
echo "  Priority: P1"
echo ""

#============= GAP 4: PSRemoting ================
echo "GAP 4: T1021.006 PowerShell Remoting"
echo "  Hunt Finding: Interactive PSRemoting sessions staged the 4x03-confirmed"
echo "    exfiltrator (sync_healthdata.ps1) onto 2 production databases (7-hunt_psremoting.sh)"
echo "  Why Missed: Rule existed but was too specific -- if any PSRemoting"
echo "    monitoring existed, it likely only watched for Enter-PSSession on the"
echo "    admin workstation, not for sessions LANDING on a server from"
echo "    somewhere else, which is the receiving-side wsmprovhost.exe signature"
echo "  Data Source: Sysmon Event 1 (Process Create) on the TARGET host"
echo "  Required Rule: alert when ParentImage=wsmprovhost.exe AND the"
echo "    authenticated user is not in the documented-administrator baseline,"
echo "    OR when a Copy-Item/file-transfer command appears inside a"
echo "    wsmprovhost.exe-parented process"
echo "  Priority: P1 -- this is the staging step that would have given the"
echo "    earliest warning of planned data exfiltration"
echo ""

#============= GAP 5: Service Account Misuse ================
echo "GAP 5: T1078.002 Service Account Misuse"
echo "  Hunt Finding: svc_healthsync authenticated via NTLM from a workstation"
echo "    6 times, violating the authorization matrix in every instance (9-hunt_svcaccount.sh)"
echo "  Why Missed: Missing data correlation, not missing data -- Event 4624"
echo "    was being collected (846 svc_healthsync auth events exist in 14"
echo "    days), but nothing cross-referenced TargetUserName against the"
echo "    service account's documented authorized host"
echo "  Data Source: Windows Event 4624 (Successful Logon)"
echo "  Required Rule: alert when TargetUserName matches ^svc_ AND"
echo "    WorkstationName matches ^WS- (any workstation), OR LogonType IN"
echo "    (2,10,11), OR AuthenticationPackageName=NTLM -- this is the"
echo "    single most reliable rule in this whole gap list: the service"
echo "    account authorization matrix admits ZERO legitimate exceptions"
echo "  Priority: P1 -- highest-confidence, lowest-false-positive rule available"
echo ""

#============= GAP 6: NTLM / Pass-the-Hash ================
echo "GAP 6: T1550.002 NTLM / Pass-the-Hash-style Activity"
echo "  Hunt Finding: all 6 unauthorized svc_healthsync authentications used"
echo "    NTLM instead of the account's documented Kerberos-only policy"
echo "  Why Missed: Missing rule -- this is the SAME underlying Event 4624"
echo "    data as Gap 5, evaluated on a different field (AuthenticationPackageName)"
echo "  Data Source: Windows Event 4624, AuthenticationPackageName field"
echo "  Required Rule: alert on ANY service account authentication using"
echo "    NTLM rather than Kerberos, domain-wide, regardless of source host"
echo "  Priority: P2 -- this rule is evidence-honest, not overclaimed: NTLM"
echo "    usage is consistent with pass-the-hash but does not, by itself,"
echo "    prove a hash (vs. a recovered plaintext password) was used -- see"
echo "    11-attack_update.sh, which deliberately left T1550.002 as INFERRED"
echo "    rather than upgrading it to OBSERVED on this evidence alone"
echo ""

echo "SUMMARY:"
echo "  The data was present for every gap above -- Sysmon Event 1/10 and"
echo "  Windows Event 4624 were all being collected throughout the hunt"
echo "  window. The detection logic was missing (or, for PSRemoting,"
echo "  present but scoped to the wrong side of the connection)."
echo "  Proactive hunting exposed the gap; no new telemetry had to be"
echo "  deployed to close it -- only new rules, which is exactly what"
echo "  13-detection_rules.sh produces."
echo ""
echo "================================================================"
