#!/bin/bash
set -euo pipefail

SHIFT_WORKSPACE="${SHIFT_WORKSPACE:-$HOME/bt/3x05/shift_pack}"

fail() {
	echo "[handoff] FAIL: $1" >&2
	exit 1
}

REQUIRED_FILES=(
	MANIFEST.json
	runtime/shift_start.json runtime/pipeline_run.json runtime/baseline_run.json runtime/catalog_run.json
	enriched/enriched_events.jsonl enriched/timeline.jsonl enriched/baseline.json enriched/source_stats.json
	alerts/alert_queue.json alerts/shift_briefing.json alerts/triage_log.jsonl alerts/incidents.json
	investigations/incident_A.json investigations/incident_B.json investigations/incident_C_cli.json investigations/incident_C_export.json
	campaign/campaign_assessment.json
	reports/incident_A.md reports/incident_B.md reports/incident_C.md
	response/tuning_recommendations.json response/containment.json response/ioc_package.json
	handoff/shift_handoff.md
)

# MANIFEST.json and handoff/shift_handoff.md are generated by this same
# script, so they are allowed to be absent/empty on this pass; every other
# file must already exist and be non-empty before the handoff can be
# assembled.
CHECKED=0
for F in "${REQUIRED_FILES[@]}"; do
	[ "$F" = "MANIFEST.json" ] && continue
	[ "$F" = "handoff/shift_handoff.md" ] && continue
	[ -s "$SHIFT_WORKSPACE/$F" ] || fail "missing or empty: $F"
	CHECKED=$((CHECKED + 1))
done
printf "[handoff] checking workspace layout... %s files OK\n" "$CHECKED"

SHIFT_START_FILE="$SHIFT_WORKSPACE/runtime/shift_start.json"
SHIFT_ID="$(jq -r '.shift_id' "$SHIFT_START_FILE")"
ANALYST_HOST="$(jq -r '.analyst_host' "$SHIFT_START_FILE")"
STARTED_AT="$(jq -r '.started_at' "$SHIFT_START_FILE")"
ENDED_AT="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
printf "[handoff] shift_id: %s\n" "$SHIFT_ID"

DURATION_HOURS="$(python3 -c "
from datetime import datetime
s = datetime.fromisoformat('$STARTED_AT'.replace('Z','+00:00'))
e = datetime.fromisoformat('$ENDED_AT'.replace('Z','+00:00'))
print(round((e - s).total_seconds() / 3600, 2))
")"
printf "[handoff] duration: %s hours\n" "$DURATION_HOURS"

INCIDENTS_FILE="$SHIFT_WORKSPACE/alerts/incidents.json"
INCIDENT_IDS_JSON="$(jq '[.incidents[].incident_id]' "$INCIDENTS_FILE")"

CAMPAIGN_FILE="$SHIFT_WORKSPACE/campaign/campaign_assessment.json"
CAMPAIGN_LINKED="$(jq -r '.campaign_linked' "$CAMPAIGN_FILE")"
CLUSTER_ID="$(jq -r '.cluster_id' "$CAMPAIGN_FILE")"

IOC_COUNT="$(jq -r '.ioc_count' "$SHIFT_WORKSPACE/alerts/shift_briefing.json")"
TP_COUNT="$(jq -c 'select(.classification=="TP")' "$SHIFT_WORKSPACE/alerts/triage_log.jsonl" | wc -l | tr -d ' ')"
ALERTS_TOTAL="$(jq 'length' "$SHIFT_WORKSPACE/alerts/alert_queue.json")"

HANDOFF_MD="$SHIFT_WORKSPACE/handoff/shift_handoff.md"

cat > "$HANDOFF_MD" <<EOF
# Shift Handoff — $SHIFT_ID

## Shift Identifier

Shift ID: $SHIFT_ID. Analyst host: $ANALYST_HOST. Started: $STARTED_AT. Ended: $ENDED_AT. Duration: $DURATION_HOURS hours.

## Situation

MedDefense activated heightened monitoring after an H-ISAC advisory tied the HC-RED7 activity cluster to three confirmed regional hospital intrusions over the prior six weeks. This shift ran the full detection chain (pipeline, baseline, catalog, triage) against an 8-day, ~339,287-event evidence pack (2026-04-01 to 2026-04-08) covering 16 hosts across three sites, with a $IOC_COUNT-entry IOC feed cross-referenced throughout. The catalog produced $ALERTS_TOTAL alerts from one rule; triage classified $TP_COUNT of them as true positive.

## Incidents

No incident reached true-positive status this shift ($TP_COUNT confirmed TPs out of $ALERTS_TOTAL alerts), so no incident IDs are logged in alerts/incidents.json. The "A", "B", and "C" investigation slots were each still worked and documented: reports/incident_A.md, reports/incident_B.md, and reports/incident_C.md each record a null-result investigation with the specific searches performed and their evidence. Slot A ruled out an SSH/RDP brute-force cluster and the advisory's named C2/service indicators (none present in the raw evidence). Slot B ruled out the expected change-ticket ambiguity case because the ticketed host (rad-srv-02) does not exist in this pack's technical evidence. Slot C found that the Wazuh export artifacts for this incident reference the wrong evidence pack entirely (3x04's primary pack, not this capstone's data).

## Campaign Assessment

campaign_linked is $CAMPAIGN_LINKED, cluster_id is $CLUSTER_ID, per campaign/campaign_assessment.json. With zero confirmed TP incidents, there is no pairwise IOC, tactic, or temporal overlap to evaluate, so no campaign linkage can be asserted from this shift's own evidence. The Wazuh export view (campaign_dashboard_summary.md) separately claims campaign_linked=true with high confidence, but that verdict is built on search results with hits_total=0 against hosts absent from this pack — it is not corroborating evidence and should not be relied on until the export is regenerated correctly.

## Open Items for Next Shift

- Add a Sigma rule for Windows service installation (event_id 7045) to cover T1543.003 persistence — see response/tuning_recommendations.json TUNE-001.
- Add a Sigma rule for irregular-interval outbound beaconing to cover T1071.001 C2 — see TUNE-002; a manual firewall.csv sweep for 8-15 minute beacon pairs found none.
- Re-tune rule 002 (off-hours privileged logon) to require privileged group membership — it produced $ALERTS_TOTAL noisy alerts this shift with no differentiating signal — see TUNE-003.
- Recover the LogonType field in the 3x00 pipeline's normalized schema — dropped during normalization, which broke rule 002's original selection — see TUNE-004.
- Request regeneration of hc_red7_advisory.md, change_tickets.json, prior_shift_notes.md, and wazuh_exports/* against evidence_pack_secondary — every named host and IOC in the current versions is absent from the actual pack — see TUNE-005.
- Confirm whether the H-ISAC advisory's HC-RED7 activity is present in this specific evidence window at all, given no technical indicator for it was found despite systematic search.

## Artifact Index

See MANIFEST.json for the complete file list with sha256 hashes and sizes.
EOF

WORD_COUNT="$(wc -w < "$HANDOFF_MD" | tr -d ' ')"
[ "$WORD_COUNT" -le 900 ] || fail "shift_handoff.md is $WORD_COUNT words, exceeds the 900-word cap"
printf "[handoff] shift_handoff.md: %s words\n" "$WORD_COUNT"

REQUIRED_HEADINGS=("## Shift Identifier" "## Situation" "## Incidents" "## Campaign Assessment" "## Open Items for Next Shift" "## Artifact Index")
for H in "${REQUIRED_HEADINGS[@]}"; do
	grep -qF "$H" "$HANDOFF_MD" || fail "missing required heading: $H"
done
printf "[handoff] %s sections OK\n" "${#REQUIRED_HEADINGS[@]}"

# every incident ID cited in the handoff must exist in incidents.json (there are none of either, so this holds vacuously)
CITED_IDS="$(grep -oE 'INC-[0-9]{8}-[A-Z]' "$HANDOFF_MD" | sort -u || true)"
if [ -n "$CITED_IDS" ]; then
	while IFS= read -r ID; do
		echo "$INCIDENT_IDS_JSON" | jq -e --arg id "$ID" 'index($id)' >/dev/null || fail "handoff cites $ID, not present in incidents.json"
	done <<< "$CITED_IDS"
fi
printf "[handoff] incident IDs in handoff: none cited (0 confirmed incidents)\n"

# --- MANIFEST.json ---
MANIFEST_ENTRIES="[]"
while IFS= read -r -d '' FILE_PATH; do
	REL_PATH="${FILE_PATH#"$SHIFT_WORKSPACE"/}"
	[ "$REL_PATH" = "MANIFEST.json" ] && continue
	[[ "$REL_PATH" == .* ]] && continue
	SIZE="$(stat -c%s "$FILE_PATH")"
	SHA="$(sha256sum "$FILE_PATH" | cut -d' ' -f1)"
	ENTRY="$(jq -n --arg path "$REL_PATH" --arg sha256 "$SHA" --argjson size "$SIZE" '{path: $path, sha256: $sha256, size: $size}')"
	MANIFEST_ENTRIES="$(echo "$MANIFEST_ENTRIES" | jq --argjson e "$ENTRY" '. + [$e]')"
done < <(find "$SHIFT_WORKSPACE" -maxdepth 1 -type d ! -path "$SHIFT_WORKSPACE" -exec find {} -type f -print0 \; ; find "$SHIFT_WORKSPACE" -maxdepth 1 -type f -print0)

ARTIFACT_COUNTS="$(jq -n --argjson entries "$MANIFEST_ENTRIES" '
	["runtime","enriched","alerts","investigations","campaign","reports","response","handoff"] as $dirs
	| reduce $dirs[] as $d ({}; . + {($d): ($entries | map(select(.path | startswith($d + "/"))) | length)})
')"

TOTAL_KB="$(echo "$MANIFEST_ENTRIES" | jq '[.[].size] | add / 1024 | floor')"
FILE_COUNT="$(echo "$MANIFEST_ENTRIES" | jq 'length')"

jq -n \
	--arg shift_id "$SHIFT_ID" \
	--arg analyst_host "$ANALYST_HOST" \
	--arg started_at "$STARTED_AT" \
	--arg ended_at "$ENDED_AT" \
	--argjson duration_hours "$DURATION_HOURS" \
	--argjson files "$MANIFEST_ENTRIES" \
	--argjson artifact_counts "$ARTIFACT_COUNTS" \
	--argjson incident_ids "$INCIDENT_IDS_JSON" \
	--argjson campaign_linked "$CAMPAIGN_LINKED" \
	--arg cluster_id "$CLUSTER_ID" \
	'{
		shift_id: $shift_id,
		analyst_host: $analyst_host,
		started_at: $started_at,
		ended_at: $ended_at,
		duration_hours: $duration_hours,
		files: $files,
		artifact_counts: $artifact_counts,
		incident_ids: $incident_ids,
		campaign_linked: $campaign_linked,
		cluster_id: $cluster_id
	}' > "$SHIFT_WORKSPACE/MANIFEST.json"

printf "[handoff] MANIFEST.json: %s files, %s KB total\n" "$FILE_COUNT" "$TOTAL_KB"
printf "[handoff] campaign_linked=%s cluster=%s\n" "$CAMPAIGN_LINKED" "$CLUSTER_ID"
printf "[handoff] handoff package complete\n"
