#!/bin/bash
#
# 4-nftables_config.sh
#
# MedDefense Health Systems - Perimeter and Network Defense (2x04)
#
# T2 defined the rules. This enforces them. nftables is less forgiving than
# iptables: one wrong atomic ruleset update can lock you out of your own
# SSH session in one second. This script renders, check-parses (`nft -c`),
# backs up the current ruleset for rollback, and only then applies.
#
# Safety note (read this before editing): the lab/management access path to
# this host (the hypervisor's NAT interface, whatever it is named) is
# treated as out-of-band and is EXPLICITLY exempted from the zone model,
# the same way a real production host has an iLO/IPMI/OOB NIC that sits
# outside the segmented production network. Everything else is enforced
# strictly from segmentation_rules.json. See MGMT_ACCESS_IFACE below.
#
# Zone names (DMZ, INTERNAL, MGMT, MEDDEV) are never hardcoded below - every
# set, chain rule and comment is rendered from the four zones defined in
# segmentation_rules.json, so this script stays correct if T2's zone model
# ever changes.
#
# Usage: sudo ./4-nftables_config.sh [--render-only] [segmentation_rules.json]
# Env:   MGMT_ACCESS_IFACE   interface to always allow SSH on, out-of-band
#                             (default: auto-detected as the interface
#                             carrying this SSH session's local address)

set -uo pipefail

RENDER_ONLY="false"
if [ "${1:-}" = "--render-only" ]; then
    RENDER_ONLY="true"
    shift
fi
RULES_JSON="${1:-segmentation_rules.json}"
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
CONF_FILE="${SCRIPT_DIR}/nftables.conf"

resolve_input() {
    local name="$1" candidate
    for candidate in "./${name}" "${SCRIPT_DIR}/${name}" "${SCRIPT_DIR}/../${name}"; do
        [ -f "$candidate" ] && { echo "$candidate"; return 0; }
    done
    echo "$name"
}
[ -f "$RULES_JSON" ] || RULES_JSON="$(resolve_input segmentation_rules.json)"
if [ ! -r "$RULES_JSON" ]; then
    echo "error: cannot read $RULES_JSON (run 2-segmentation_rules.sh first)" >&2
    exit 1
fi

# --- Auto-detect the out-of-band management interface -----------------------
# The interface that currently carries an established tcp/22 session is
# assumed to be the lab/hypervisor access path, not part of the modeled
# MedDefense production network - never let the zone model block it.
if [ -z "${MGMT_ACCESS_IFACE:-}" ]; then
    ssh_local_ip="$(ss -tnpH state established 2>/dev/null | awk '$3 ~ /:22$/ {print $3}' | awk -F: '{print $1}' | head -1)"
    MGMT_ACCESS_IFACE="$(ip -o -4 addr show 2>/dev/null | awk -v ip="$ssh_local_ip" '$4 ~ "^"ip"/" {print $2}' | head -1)"
fi
if [ -z "$MGMT_ACCESS_IFACE" ]; then
    echo "error: could not auto-detect the out-of-band access interface." >&2
    echo "       Set MGMT_ACCESS_IFACE=<iface> explicitly and re-run - refusing to" >&2
    echo "       render a ruleset that might lock out the current session." >&2
    exit 1
fi
echo "[*] Out-of-band management access exempted on interface: $MGMT_ACCESS_IFACE"

# --- Which zone does this host belong to? -----------------------------------
# Pure-bash CIDR containment: convert dotted IP and network to 32-bit ints.
ip_to_int() {
    local IFS=. a b c d
    read -r a b c d <<<"$1"
    echo $(( (a << 24) + (b << 16) + (c << 8) + d ))
}
ip_in_cidr() {
    local ip="$1" cidr="$2" net prefix ip_int net_int mask
    net="${cidr%/*}"; prefix="${cidr#*/}"
    ip_int="$(ip_to_int "$ip")"
    net_int="$(ip_to_int "$net")"
    mask=$(( prefix == 0 ? 0 : (0xFFFFFFFF << (32 - prefix)) & 0xFFFFFFFF ))
    [ $(( ip_int & mask )) -eq $(( net_int & mask )) ]
}

mapfile -t HOST_IPS < <(ip -o -4 addr show 2>/dev/null | awk -v skip="$MGMT_ACCESS_IFACE" '$2!=skip {split($4,a,"/"); print a[1]}')
HOST_ZONE=""
mapfile -t ZONE_NAMES < <(jq -r '.zones[].name' "$RULES_JSON")
for zname in "${ZONE_NAMES[@]}"; do
    zcidr="$(jq -r --arg z "$zname" '.zones[] | select(.name==$z) | .cidr' "$RULES_JSON")"
    for hip in "${HOST_IPS[@]}"; do
        if ip_in_cidr "$hip" "$zcidr"; then
            HOST_ZONE="$zname"
            break 2
        fi
    done
done
[ -z "$HOST_ZONE" ] && { echo "error: this host's address does not match any zone in $RULES_JSON" >&2; exit 1; }
echo "[*] This host belongs to zone: $HOST_ZONE"

# --- Render nftables.conf ----------------------------------------------------
{
    echo "#!/usr/sbin/nft -f"
    echo "# Generated by 4-nftables_config.sh from $RULES_JSON - do not edit by hand."
    echo "flush ruleset"
    echo ""
    echo "table inet meddefense {"

    jq -r '.zones[] | "    set \(.name | ascii_downcase)_net { type ipv4_addr; flags interval; elements = { \(.cidr) } }"' "$RULES_JSON"
    echo ""

    echo "    chain input {"
    echo "        type filter hook input priority 0; policy drop;"
    echo "        iif \"lo\" accept"
    echo "        ct state established,related accept"
    echo "        ct state invalid drop"
    echo "        icmp type { echo-request, destination-unreachable, time-exceeded } accept"
    echo "        icmpv6 type { echo-request, nd-neighbor-solicit, nd-neighbor-advert } accept"
    echo "        iifname \"$MGMT_ACCESS_IFACE\" tcp dport 22 accept comment \"lab/OOB management access - not part of the MedDefense zone model\""
    echo ""
    echo "        # Flows that terminate on this host ($HOST_ZONE zone)"
    # A flow's src_hosts, when present, is a real restriction (e.g. "only
    # from these named DMZ app hosts") - it must narrow the match to those
    # literal addresses, not the whole source zone, or the "named hosts
    # only" promise in segmentation_rules.json is silently not enforced.
    jq -r --arg hz "$HOST_ZONE" '
        .flows[] | select(.dst_zone == $hz)
        | (if .src_hosts != null and (.src_hosts | length) > 0
           then "{ " + (.src_hosts | join(", ")) + " }"
           else "@\(.src_zone | ascii_downcase)_net" end) as $src
        | "        ip saddr \($src) \(.proto) dport \(.dport) accept comment \"\(.justification)\""
    ' "$RULES_JSON"
    echo ""
    echo "        log prefix \"meddefense-in-drop: \" drop"
    echo "    }"
    echo ""

    echo "    chain forward {"
    echo "        type filter hook forward priority 0; policy drop;"
    echo "        ct state established,related accept"
    echo "        ct state invalid drop"
    jq -r '
        .flows[] | select(.src_zone != .dst_zone)
        | (if .src_hosts != null and (.src_hosts | length) > 0
           then "{ " + (.src_hosts | join(", ")) + " }"
           else "@\(.src_zone | ascii_downcase)_net" end) as $src
        | "        ip saddr \($src) ip daddr @\(.dst_zone | ascii_downcase)_net \(.proto) dport \(.dport) accept comment \"\(.justification)\""
    ' "$RULES_JSON"
    echo ""
    echo "        log prefix \"meddefense-fwd-drop: \" drop"
    echo "    }"
    echo ""

    echo "    chain output {"
    echo "        type filter hook output priority 0; policy accept;"
    echo "        oif \"lo\" accept"
    echo "        # This host ($HOST_ZONE) must not originate traffic to zones it has no allow flow into."
    jq -r --arg hz "$HOST_ZONE" '
        [.zones[].name] as $all
        | [$all[] | select(. != $hz)] as $others
        | ($others - [.flows[] | select(.src_zone == $hz) | .dst_zone]) as $forbidden
        | $forbidden[] | "        ip daddr @\(. | ascii_downcase)_net log prefix \"meddefense-out-drop: \" drop"
    ' "$RULES_JSON"
    echo "    }"
    echo "}"
} > "$CONF_FILE"

echo "[*] Rendered $CONF_FILE"

# --- Check-only parse before touching anything -------------------------
if ! nft -c -f "$CONF_FILE"; then
    echo "[!] nft -c (check-only) failed - ruleset NOT applied." >&2
    exit 1
fi
echo "[*] nft -c check-only parse: OK"

if [ "$RENDER_ONLY" = "true" ]; then
    echo "[*] --render-only: stopping before rollback backup / apply."
    exit 0
fi

# --- Rollback point -----------------------------------------------------
# Save a rollback of the current ruleset before applying:
#   nft list ruleset > /var/backups/nftables-rollback-<timestamp>.nft
# `nft list ruleset` prints `add table`/`add chain`/`add rule` statements
# only - it never includes a `flush ruleset` line. Restoring it with a bare
# `nft -f rollback.nft` therefore layers the old rules on top of whatever is
# currently loaded instead of replacing it - on a host with no ruleset at
# all beforehand (the common case), the "rollback" file is empty and
# restoring it is a silent no-op that leaves the new ruleset in place. A
# real rollback has to flush first, so `flush ruleset` is prepended here and
# the restore command documented below always flushes before loading.
TS="$(date -u +%Y%m%dT%H%M%SZ)"
BACKUP_DIR="/var/backups"
mkdir -p "$BACKUP_DIR"
ROLLBACK_FILE="${BACKUP_DIR}/nftables-rollback-${TS}.nft"
{ echo "flush ruleset"; nft list ruleset 2>/dev/null; } > "$ROLLBACK_FILE"
echo "[*] Current ruleset backed up to $ROLLBACK_FILE"

# --- Apply atomically -----------------------------------------------------
if ! nft -f "$CONF_FILE"; then
    echo "[!] nft -f failed to apply - restoring rollback" >&2
    nft -f "$ROLLBACK_FILE"
    exit 1
fi
echo "[*] Applied $CONF_FILE"

# Verify the load with `nft list ruleset` and count the rules that match
# the expected total: every rule/set line this script rendered into
# CONF_FILE must show up as a loaded handle in the live "inet meddefense"
# table, or the atomic apply silently dropped something.
EXPECTED_COUNT="$(grep -cE '^        (iif |iifname |oif |ct state|icmp type|icmpv6 type|ip saddr|ip daddr|log prefix)' "$CONF_FILE")"
RULE_COUNT="$(nft -a list table inet meddefense | grep -c '# handle')"
echo "[*] Ruleset loaded: $RULE_COUNT rule handles present (expected $EXPECTED_COUNT from render)"
if [ "$RULE_COUNT" -eq "$EXPECTED_COUNT" ]; then
    echo "[*] Loaded rule count matches expected total."
else
    echo "[!] WARNING: loaded rule count ($RULE_COUNT) does not match the expected total ($EXPECTED_COUNT)." >&2
fi
echo "[*] Rollback path if needed: sudo nft -f $ROLLBACK_FILE   (already includes 'flush ruleset')"
